### ISSUE TITLE
Build a replica without a custom docker-entrypoint.sh

### ISSUE THREAD

**Issue by kennard-yea** [kennard-yea/Docker-PostgreSQL#29]
It should be possible to create a simple script for building a replica then placing it in docker-entrypoint-initdb.d. Customizing parameter should not use a custom entrypoint either. That way upstream changes to the script from the postgres image can be accepted.

**Comment by kennard-yea** [comment]
### TODO Brainstorm

- [ ] Generate a .pgpass file for the user to access the primary host/port instead of relying on environment variables in postgresql.auto.conf
- [ ] Use $REPLICATION_USER and $REPLICATION_PASSWORD environment variables so a separate user may be specified for repliction
- [ ] Loop with a timeout to make sure the primary is initialized properly before running a base backup
